// Code generated by go2go; DO NOT EDIT.


//line min_heap.go2:1
package prioqueue

//line min_heap.go2:1
import (
//line min_heap.go2:1
 "github.com/stretchr/testify/assert"
//line min_heap.go2:1
 "github.com/stretchr/testify/require"
//line min_heap.go2:1
 "math/rand"
//line min_heap.go2:1
 "testing"
//line min_heap.go2:1
)

//line min_heap.go2:1
type Importable୦ int

//line min_heap.go2:1
var _ = assert.AnError

//line min_heap.go2:1
type _ require.Assertions

//line min_heap.go2:1
var _ = rand.ExpFloat64
//line min_heap.go2:1
var _ = testing.AllocsPerRun
