name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - 'main'

jobs:
  unit_tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.22

      - name: Test
        run: go test -v -cover -coverprofile=coverage.txt -covermode=count -mod=readonly ./...

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage.txt

  code_coverage:
    name: "Code coverage report"
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - uses: fgrosse/go-coverage-report@751163467e865a37a50cc964f6397a7cb469287b
        with:
          coverage-artifact-name: "code-coverage"
          coverage-file-name: "coverage.txt"
