name: CI

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  unit_tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.22

      - name: Test
        run: go test -v -cover -coverprofile=coverage.txt -covermode=count -mod=readonly ./...

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage.txt

  code_coverage:
    name: "Code coverage report"
    runs-on: ubuntu-latest
    needs: unit_tests
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Install go-coverage-report
        run: |
          go env
          go install github.com/fgrosse/go-coverage-report@v0.1.0
          ls -l $HOME/go/bin
          ls -l $GOPATH/bin

      - name: Determine changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          write_output_files: true
          json: true
          files: |
            **.go
          files_ignore: |
            **_test.go
            vendor/**

      - name: Verify the contents of the .github/outputs/added_files.txt file
        run: |
          cat .github/outputs/all_changed_files.json

      - name: Download code coverage results from target branch # TODO: download from latest successful run on the target branch instead of main branch
        run: |
          gh run download --name=code-coverage
          mv coverage.txt old-coverage.txt

      - name: Download code coverage results
        uses: actions/download-artifact@v4
        with:
          name: code-coverage
          path: new-coverage.txt

      - name: Compare code coverage results
        run: |
          go-coverage-report \
            -prefix=github.com/fgrosse/prioqueue \
            old-coverage.txt \
            new-coverage.txt \
            .github/outputs/all_changed_files.json \
          > coverage-comment.md

      - name: Comment on pull request
        run: gh pr comment ${{ github.event.number }} --body-file=coverage-comment.md
